// This file was auto-generated by ML.NET Model Builder. 

using System;
using EpidemicProjectML.Model;

namespace EpidemicProjectML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Ds = 100F,
                Di = 1F,
                Dr = 0F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Dt with predicted Dt from sample data...\n\n");
            Console.WriteLine($"Ds: {sampleData.Ds}");
            Console.WriteLine($"Di: {sampleData.Di}");
            Console.WriteLine($"Dr: {sampleData.Dr}");
            Console.WriteLine($"\n\nPredicted Dt: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
