// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace EpidemicProjectML.Model
{
    public class ModelInput
    {
        [ColumnName("Dt"), LoadColumn(0)]
        public float Dt { get; set; }


        [ColumnName("Ds"), LoadColumn(1)]
        public float Ds { get; set; }


        [ColumnName("Di"), LoadColumn(2)]
        public float Di { get; set; }


        [ColumnName("Dr"), LoadColumn(3)]
        public float Dr { get; set; }


    }
}
